services:
  role-bot:
    build: .
    image: registry.nemahs.org/primary-role

    environment:
      RUST_LOG: "warn,discord_bot=info"

    secrets:
      - DISCORD_TOKEN

    volumes:
      - bot_data:/app/data

    deploy:
      replicas: 1

secrets:
  DISCORD_TOKEN:
    external:
      true


volumes:
  bot_data: